### ISSUE TITLE
Linguee French-to-English translation not working

### ISSUE THREAD

**Issue by wf001** [nidhaloff/deep-translator#176]
# Linguee French-to-English translation not working
* deep_translator version:v1.9.1(https://github.com/nidhaloff/deep-translator/commit/a694c92b6741fc9c3200835b64be2fd910cd761b)
* Python version: 3.10.6
* Operating System: GNU/Linux x86_64(Ubuntu 22.04)

### Description
Hi, thank you for publishing such a useful plugin!
I noticed that Linguee’s French-to-English translation didn’t work. And it seems that English-to-French, French-to-German, German-to-French also doesn’t work.
I suspect it’s because the URL format of Linguee(such as path and query) has been changed as following.

the URL deep-translator using
```
https://www.linguee.com/fr-en/translation/courir.html
```

the correct(and valid) URL
```
https://www.linguee.com/english-french/search?source=french&query=courir
```
If you guys are OK, I would be interested in contributing this.

### What I Did
(expected returning 'run')
```
>>> from deep_translator import LingueeTranslator
>>> res = LingueeTranslator(source="fr", target="en").translate("courir", return_all=False)                        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/share-ws/common/deep-translator/deep_translator/linguee.py", line 77, in translate
    raise ElementNotFoundInGetRequest(elements)
deep_translator.exceptions.ElementNotFoundInGetRequest: [] --> Required element was not found in the API response

```

**Comment by wf001** [comment]
Tried to fix this, send PR. See https://github.com/nidhaloff/deep-translator/pull/179.
