### ISSUE TITLE
Too many request with MyMemoryTranslator?

### ISSUE THREAD

**Issue by Khyretos** [nidhaloff/deep-translator#253]
* deep_translator version: 1.11.4
* Python version: 3.11.4
* Operating System: Windows 10

### Description

I thaught MyMemoryTranslator was free, i understand it is not then?
![image](https://github.com/nidhaloff/deep-translator/assets/25864917/a56c2524-14c7-451c-b3fb-d71d4a04241d)

### What I Did

```py
from deep_translator import (GoogleTranslator,
                             ChatGptTranslator,
                             MicrosoftTranslator,
                             PonsTranslator,
                             LingueeTranslator,
                             MyMemoryTranslator,
                             YandexTranslator,
                             PapagoTranslator,
                             DeeplTranslator,
                             QcriTranslator,
                             single_detection,
                             batch_detection)
translated = MyMemoryTranslator(
    source="nl-NL", target="es-ES"
).translate("hallo, mijn naam is kees")

print(translated)
```

```shell
Traceback (most recent call last):
  File "c:\repos\LoquendoBotV2\test.py", line 15, in <module>
    ).translate("hallo, mijn naam is kees")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\deep_translator\mymemory.py", line 73, in translate
    raise TooManyRequests()
deep_translator.exceptions.TooManyRequests: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the
and try again later oryou can try the translate_batch function
```

**Comment by Khyretos** [comment]
never mind, i saw the rate limit. thank you for the tool.
