### ISSUE TITLE
`KeyError: 'hl'` when running `translate_batch()`

### ISSUE THREAD

**Issue by vardecab** [nidhaloff/deep-translator#41]
* deep_translator version: 1.3.9
* Python version: 3.7.4
* Operating System: Windows 10

### Description

I couldn't translate 2000+ words from a text file (described in here #40) so I thought about using `translate_batch()` instead. Running: 
```python
translated_list = GoogleTranslator(select_source_language, select_target_language).translate_batch(list_of_words)
```
gives me this error: 
```python
Traceback (most recent call last):
  File "script.py", line 113, in <module>
    translated_list = GoogleTranslator(select_source_language, select_target_language).translate_batch(list_of_words)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\deep_translator\google_trans.py", line 169, in translate_batch
    translated = self.translate(text)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\deep_translator\google_trans.py", line 113, in translate
    return self.translate(text)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\deep_translator\google_trans.py", line 112, in translate
    del self._url_params["hl"]
KeyError: 'hl'
```
What's the reason behind it? How to make it work?

**Comment by nidhaloff** [comment]
Can you show your example? what did you pass as arguments? a list of strings?

**Comment by vardecab** [comment]
Code looks like this - I'm passing a list of 2188 strings:
```python
…
print(type(single_words)) # => <class 'list'>
print(len(single_words)) # => 2188
translated_list = GoogleTranslator(select_source_language, select_target_language).translate_batch(single_words)
…
```
List looks like this (partial screenshot): 
![WindowsTerminal_fN04QtrHFn](https://user-images.githubusercontent.com/6877391/110246921-e7ab7800-7f69-11eb-8466-3d89da544b5b.png)

The error looks like this:
```
Please wait.. This may take a couple of seconds because deep_translator sleeps for two seconds after each request in order to not spam the google server.
sentence number  1  has been translated successfully
sentence number  2  has been translated successfully
Traceback (most recent call last):
  File "script.py", line 122, in <module>
    translated_list = GoogleTranslator(select_source_language, select_target_language).translate_batch(single_words)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\deep_translator\google_trans.py", line 171, in translate_batch
    translated = self.translate(text)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\deep_translator\google_trans.py", line 113, in translate
    return self.translate(text)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\deep_translator\google_trans.py", line 112, in translate
    del self._url_params["hl"]
KeyError: 'hl'
```

**Comment by nidhaloff** [comment]
@vardecab Alright. Thanks for posting this. This appears to be a bug, I will check it out asap

**Comment by nidhaloff** [comment]
can you post your source and target languages? I tried your example and it worked fine! maybe it has something to do with the chosen language

**Comment by vardecab** [comment]
Hmmm... Could it be due to special characters or non-letter characters in the list? 

> can you post your source and target languages? I tried your example and it worked fine! maybe it has something to do with the chosen language

English as source, Polish as target.

```python
select_source_language = 'en'
select_target_language = 'pl'
```

**Comment by nidhaloff** [comment]
@vardecab special characters are actually ok ;)  I conducted a bug fixes in the new release -> 1.4.1 

make sure you try it out. I think it will solve this issue

**Comment by vardecab** [comment]
Updated to the latest version:
```python
pip show deep-translator
Name: deep-translator
Version: 1.4.1
```

Ran code:
```python
translated_list = GoogleTranslator(select_source_language, select_target_language).translate_batch(single_words)
```
Got error:
```
raise NotValidPayload(payload)
deep_translator.exceptions.NotValidPayload: 1 --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated
```

So it looks like it's the 5000-character-limit again, similar to #40.

**Comment by nidhaloff** [comment]
@vardecab I will close this issue since it is actually solved.  As I said you probably need to filter your list and let only words or sentences that can be translated. Feel free to re-open if you faced any issues

**Comment by vardecab** [comment]
Cleaning the list solved the issue - that's correct. **List can't have any special characters, numbers of single characters - otherwise translation will fail.** 

Thanks for your support and good logs! :)


PS
> you cant translate the number 1 can you?

I can't "translate" the number but Google Translate doesn't reject a numerical input, so one can argue that your package should support sending numbers to the API. The returned value will be the same, because it's the same number in every country, but at least this behavior will be in line with what translators are doing.
![brave_3PsYNUUyi6](https://user-images.githubusercontent.com/6877391/110517580-5411ad00-810b-11eb-89fe-74f9049adb94.png)
![brave_YTZqLCB3HO](https://user-images.githubusercontent.com/6877391/110517584-54aa4380-810b-11eb-8e39-26ba6b07b146.png)

**Comment by nidhaloff** [comment]
@vardecab the issue is not that google translate does not allow numbers. It does but other translators don't, so to reduce the amount of code I'm using, I used a pattern where I define a similar function in a parent/base translator. You can check the code for this. 

Besides, It would be a huge problem if I allowed the translated_text (the response of the API) to be equal to the text (that I want to translate), because then I will not recognize whether there was an issue with the translation itself. For example check this issue: https://github.com/nidhaloff/deep-translator/issues/39
Here the text is not being translated and the return value is the same as the text the user wishes to translate. This is a weird behaviour and should be caught and not be allowed otherwise this would be very confusing for some users
